PORT: 9089
PREFIX: api

# 正常token2小时
tokenExpire: 2
# 刷新过期时间为7天
refreshTokenExpire: 7

# 默认密码
defaultPassword: 123456

# 数据库配置
datasource:
  driverName: mysql
  host: 192.168.2.222
  port: 3306
  database: nestapi
  username: root
  password: 12300114
  charset: utf8
  loc: Asia/Shanghai
  logging: true

#企业微信配置
wxChat:
  corpsecret: YbF5JHEjAKWuO5-5nLf5xuH2R1wFc8pGBWTq0fyE12s
  CorpID: ww97588d93c357248d
  AgentId: 1000004
  Token: KxvcyR3SQqTIzAVyIQTn2
  Key: Fc3rx5pyQ4BePDDT7t5jHOvTzfdVbBDgySDhbebWDAq


# 腾讯地图api
lbsKey: LW7BZ-NB7C5--QNDSX-VCZVT-D7FQ4

# 阿里oss存储(可直接使用)
aliyunOss:
  accessKeyId: 'LTAI4FmwbKtoErzJdwfJmcmd'
  accessKeySecret: 'bu5UZXAG2dXQ6G75bzTDXoTN1VcALv'
  endpointUrl: 'oss-cn-shenzhen'
  bucketUrl: 'https://an-jia-shop.oss-cn-shenzhen.aliyuncs.com'
  bucketName: 'an-jia-shop'
  imgDefaultSize: 5
  supportImgTypes: ['.png', '.jpg', '.gif', '.jpeg']

#法大大
fadada:
  appId: 80000470
  appSecret: FQCLPQRNNIZXVLX1NQDBS10DUZJ8HNFQ
  serverUrl: https://uat-api.fadada.com/api/v5
  opencorpId: b665596642694fa39a11e22ca5cdc704