PORT: 9089
PREFIX: api

# token过期时间为7天
tokenExpire: 7

# 数据库配置
datasource:
  driverName: mongodb
  host: "localhost"
  port: 27017
  database: wintsa
  username: root
  password: 12300114
  charset: utf8
  loc: Asia/Shanghai
  logging: true




# 腾讯地图api
lbsKey: LW7BZ-NB7C5-QNDSX-VCZVT-D7FQ4

# 阿里oss存储(可直接使用)
aliyunOss:
  accessKeyId: '*'
  accessKeySecret: '*'
  endpointUrl: 'oss-cn-shenzhen'
  bucketUrl: 'https://an-jia-shop.oss-cn-shenzhen.aliyuncs.com'
  bucketName: 'an-jia-shop'
  imgDefaultSize: 5
  supportImgTypes: ['.png', '.jpg', '.gif', '.jpeg']


ipWhitelist: ['111.229.217.225','111.231.141.181','118.89.112.13','115.159.196.132','127.0.0.1','192.168.2.1','192.168.2.221']